AI:
  model: openrouter/sherlock-dash-alpha
  name: Echo
API:
  openrouter_key: 'your key here'
TTS:
  voice: Models//glados_piper_medium.onnx
UI:
  style: alt
audio:
  input_device: 12
  length_scale: 1.0
  noise_scale: 0.0
  noise_w_scale: 0.0
  normalize_audio: false
  output_device: 17
  volume: 1.0
