AI:
  model: x-ai/grok-4.1-fast:nitro
  name: Echo
API:
  openrouter_key: YOUR-OPENROUTER-KEY-HERE
TTS:
  chatbox: false
  voice: Models//glados_piper_medium.onnx
UI:
  style: default
audio:
  input_device: 2
  length_scale: 1.0
  noise_scale: 0.0
  noise_w_scale: 0.0
  normalize_audio: false
  output_device: 19
  volume: 1.0
